var layerPopulation = {
  name: "population",
  color: "#33FF42",
  invader: false,
  xml:
    "<?xml version='1.0' encoding='UTF-8'?><wps:Execute version='1.0.0' service='WPS' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.opengis.net/wps/1.0.0' xmlns:wfs='http://www.opengis.net/wfs' xmlns:wps='http://www.opengis.net/wps/1.0.0' xmlns:ows='http://www.opengis.net/ows/1.1' xmlns:gml='http://www.opengis.net/gml' xmlns:ogc='http://www.opengis.net/ogc' xmlns:wcs='http://www.opengis.net/wcs/1.1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xsi:schemaLocation='http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd'><ows:Identifier>vec:VectorToRaster</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType='text/xml' xlink:href='http://geoserver/wfs' method='POST'><wps:Body><wfs:GetFeature service='WFS' version='1.0.0' outputFormat='GML2' xmlns:invasionx='invasionx'><wfs:Query typeName='invasionx:PopMontpellier'/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>rasterWidth</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>rasterHeight</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>attribute</ows:Identifier><wps:Data><wps:LiteralData>population</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>bounds</ows:Identifier><wps:Data><wps:BoundingBoxData crs='EPSG:404000' dimensions='2'><ows:LowerCorner>735521.6723999977 6245286.445</ows:LowerCorner><ows:UpperCorner>796171.5420999974 6309461.390000001</ows:UpperCorner></wps:BoundingBoxData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType='image/tiff'><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>"
};

var layerGraveyard = {
  name: "graveyard",
  color: "#808080",
  invader: false,
  xml:
    "<?xml version='1.0' encoding='UTF-8'?><wps:Execute version='1.0.0' service='WPS' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.opengis.net/wps/1.0.0' xmlns:wfs='http://www.opengis.net/wfs' xmlns:wps='http://www.opengis.net/wps/1.0.0' xmlns:ows='http://www.opengis.net/ows/1.1' xmlns:gml='http://www.opengis.net/gml' xmlns:ogc='http://www.opengis.net/ogc' xmlns:wcs='http://www.opengis.net/wcs/1.1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xsi:schemaLocation='http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd'><ows:Identifier>vec:VectorToRaster</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType='text/xml' xlink:href='http://geoserver/wfs' method='POST'><wps:Body><wfs:GetFeature service='WFS' version='1.0.0' outputFormat='GML2' xmlns:invasionx='invasionx'><wfs:Query typeName='invasionx:GraveyardMontpellier'/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>rasterWidth</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>rasterHeight</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>attribute</ows:Identifier><wps:Data><wps:LiteralData>osm_id</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>bounds</ows:Identifier><wps:Data><wps:BoundingBoxData crs='EPSG:2154' dimensions='2'><ows:LowerCorner>757960.4628000036 6269837.977400001</ows:LowerCorner><ows:UpperCorner>782712.1789999977 6292672.7392</ows:UpperCorner></wps:BoundingBoxData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType='image/tiff'><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>"
};

var layerHospital = {
  name: "hospital",
  color: "#cd2626",
  invader: false,
  xml:"<?xml version='1.0' encoding='UTF-8'?><wps:Execute version='1.0.0' service='WPS' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.opengis.net/wps/1.0.0' xmlns:wfs='http://www.opengis.net/wfs' xmlns:wps='http://www.opengis.net/wps/1.0.0' xmlns:ows='http://www.opengis.net/ows/1.1' xmlns:gml='http://www.opengis.net/gml' xmlns:ogc='http://www.opengis.net/ogc' xmlns:wcs='http://www.opengis.net/wcs/1.1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xsi:schemaLocation='http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd'><ows:Identifier>vec:VectorToRaster</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType='text/xml' xlink:href='http://geoserver/wfs' method='POST'><wps:Body><wfs:GetFeature service='WFS' version='1.0.0' outputFormat='GML2' xmlns:invasionx='invasionx'><wfs:Query typeName='invasionx:HospitalMontpellier'/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>rasterWidth</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>rasterHeight</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>attribute</ows:Identifier><wps:Data><wps:LiteralData>osm_id</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>bounds</ows:Identifier><wps:Data><wps:BoundingBoxData crs='EPSG:2154' dimensions='2'><ows:LowerCorner>757960.4628000036 6269837.977400001</ows:LowerCorner><ows:UpperCorner>782712.1789999977 6292672.7392</ows:UpperCorner></wps:BoundingBoxData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType='image/tiff'><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>"
}

var layerWaste = {
  name: "waste",
  color: "#883b2e",
  xml:"<?xml version='1.0' encoding='UTF-8'?><wps:Execute version='1.0.0' service='WPS' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.opengis.net/wps/1.0.0' xmlns:wfs='http://www.opengis.net/wfs' xmlns:wps='http://www.opengis.net/wps/1.0.0' xmlns:ows='http://www.opengis.net/ows/1.1' xmlns:gml='http://www.opengis.net/gml' xmlns:ogc='http://www.opengis.net/ogc' xmlns:wcs='http://www.opengis.net/wcs/1.1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xsi:schemaLocation='http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd'><ows:Identifier>vec:VectorToRaster</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType='text/xml' xlink:href='http://geoserver/wfs' method='POST'><wps:Body><wfs:GetFeature service='WFS' version='1.0.0' outputFormat='GML2' xmlns:invasionx='invasionx'><wfs:Query typeName='invasionx:WasteMontpellier'/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>rasterWidth</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>rasterHeight</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>attribute</ows:Identifier><wps:Data><wps:LiteralData>objectid</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>bounds</ows:Identifier><wps:Data><wps:BoundingBoxData crs='EPSG:2154' dimensions='2'><ows:LowerCorner>757960.4628000036 6269837.977400001</ows:LowerCorner><ows:UpperCorner>782712.1789999977 6292672.7392</ows:UpperCorner></wps:BoundingBoxData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType='image/tiff'><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>"

}

var layerPension = {
  name: "pension",
  color: "#3399ff",
  invader: false,
  xml:"<?xml version='1.0' encoding='UTF-8'?><wps:Execute version='1.0.0' service='WPS' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.opengis.net/wps/1.0.0' xmlns:wfs='http://www.opengis.net/wfs' xmlns:wps='http://www.opengis.net/wps/1.0.0' xmlns:ows='http://www.opengis.net/ows/1.1' xmlns:gml='http://www.opengis.net/gml' xmlns:ogc='http://www.opengis.net/ogc' xmlns:wcs='http://www.opengis.net/wcs/1.1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xsi:schemaLocation='http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd'><ows:Identifier>vec:VectorToRaster</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType='text/xml' xlink:href='http://geoserver/wfs' method='POST'><wps:Body><wfs:GetFeature service='WFS' version='1.0.0' outputFormat='GML2' xmlns:invasionx='invasionx'><wfs:Query typeName='invasionx:PensionMontpellier'/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>rasterWidth</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>rasterHeight</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>attribute</ows:Identifier><wps:Data><wps:LiteralData>1</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>bounds</ows:Identifier><wps:Data><wps:BoundingBoxData crs='EPSG:2154' dimensions='2'><ows:LowerCorner>757960.4628000036 6269837.977400001</ows:LowerCorner><ows:UpperCorner>782712.1789999977 6292672.7392</ows:UpperCorner></wps:BoundingBoxData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType='image/tiff'><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>"

}

var layerMonument = {
  name: "monument",
  color: "#6b8e23",
  invader: false,
  xml:"<?xml version='1.0' encoding='UTF-8'?><wps:Execute version='1.0.0' service='WPS' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.opengis.net/wps/1.0.0' xmlns:wfs='http://www.opengis.net/wfs' xmlns:wps='http://www.opengis.net/wps/1.0.0' xmlns:ows='http://www.opengis.net/ows/1.1' xmlns:gml='http://www.opengis.net/gml' xmlns:ogc='http://www.opengis.net/ogc' xmlns:wcs='http://www.opengis.net/wcs/1.1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xsi:schemaLocation='http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd'><ows:Identifier>vec:VectorToRaster</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType='text/xml' xlink:href='http://geoserver/wfs' method='POST'><wps:Body><wfs:GetFeature service='WFS' version='1.0.0' outputFormat='GML2' xmlns:invasionx='invasionx'><wfs:Query typeName='invasionx:MonumentMontpellier'/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>rasterWidth</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>rasterHeight</ows:Identifier><wps:Data><wps:LiteralData>100</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>attribute</ows:Identifier><wps:Data><wps:LiteralData>1</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>bounds</ows:Identifier><wps:Data><wps:BoundingBoxData crs='EPSG:2154' dimensions='2'><ows:LowerCorner>757960.4628000036 6269837.977400001</ows:LowerCorner><ows:UpperCorner>782712.1789999977 6292672.7392</ows:UpperCorner></wps:BoundingBoxData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType='image/tiff'><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>"
}

var layerZombie = {
  name: "zombie",
  color: "#FF0000",
  invader: true
};
